/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5-dev */

#ifndef PB_MUMBLEPROTO_MUMBLE_PB_H_INCLUDED
#define PB_MUMBLEPROTO_MUMBLE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _MumbleProto_Reject_RejectType {
    MumbleProto_Reject_RejectType_None = 0,
    MumbleProto_Reject_RejectType_WrongVersion = 1,
    MumbleProto_Reject_RejectType_InvalidUsername = 2,
    MumbleProto_Reject_RejectType_WrongUserPW = 3,
    MumbleProto_Reject_RejectType_WrongServerPW = 4,
    MumbleProto_Reject_RejectType_UsernameInUse = 5,
    MumbleProto_Reject_RejectType_ServerFull = 6,
    MumbleProto_Reject_RejectType_NoCertificate = 7,
    MumbleProto_Reject_RejectType_AuthenticatorFail = 8
} MumbleProto_Reject_RejectType;

typedef enum _MumbleProto_PermissionDenied_DenyType {
    MumbleProto_PermissionDenied_DenyType_Text = 0,
    MumbleProto_PermissionDenied_DenyType_Permission = 1,
    MumbleProto_PermissionDenied_DenyType_SuperUser = 2,
    MumbleProto_PermissionDenied_DenyType_ChannelName = 3,
    MumbleProto_PermissionDenied_DenyType_TextTooLong = 4,
    MumbleProto_PermissionDenied_DenyType_H9K = 5,
    MumbleProto_PermissionDenied_DenyType_TemporaryChannel = 6,
    MumbleProto_PermissionDenied_DenyType_MissingCertificate = 7,
    MumbleProto_PermissionDenied_DenyType_UserName = 8,
    MumbleProto_PermissionDenied_DenyType_ChannelFull = 9,
    MumbleProto_PermissionDenied_DenyType_NestingLimit = 10,
    MumbleProto_PermissionDenied_DenyType_ChannelCountLimit = 11,
    MumbleProto_PermissionDenied_DenyType_ChannelListenerLimit = 12,
    MumbleProto_PermissionDenied_DenyType_UserListenerLimit = 13
} MumbleProto_PermissionDenied_DenyType;

typedef enum _MumbleProto_ContextActionModify_Context {
    MumbleProto_ContextActionModify_Context_Server = 1,
    MumbleProto_ContextActionModify_Context_Channel = 2,
    MumbleProto_ContextActionModify_Context_User = 4
} MumbleProto_ContextActionModify_Context;

typedef enum _MumbleProto_ContextActionModify_Operation {
    MumbleProto_ContextActionModify_Operation_Add = 0,
    MumbleProto_ContextActionModify_Operation_Remove = 1
} MumbleProto_ContextActionModify_Operation;

/* Struct definitions */
typedef struct _MumbleProto_QueryUsers {
    pb_callback_t ids;
    pb_callback_t names;
} MumbleProto_QueryUsers;

typedef struct _MumbleProto_RequestBlob {
    pb_callback_t session_texture;
    pb_callback_t session_comment;
    pb_callback_t channel_description;
} MumbleProto_RequestBlob;

typedef struct _MumbleProto_UDPTunnel {
    pb_callback_t packet;
} MumbleProto_UDPTunnel;

typedef struct _MumbleProto_UserList {
    pb_callback_t users;
} MumbleProto_UserList;

typedef struct _MumbleProto_ACL {
    uint32_t channel_id;
    bool has_inherit_acls;
    bool inherit_acls;
    pb_callback_t groups;
    pb_callback_t acls;
    bool has_query;
    bool query;
} MumbleProto_ACL;

typedef struct _MumbleProto_ACL_ChanACL {
    bool has_apply_here;
    bool apply_here;
    bool has_apply_subs;
    bool apply_subs;
    bool has_inherited;
    bool inherited;
    bool has_user_id;
    uint32_t user_id;
    pb_callback_t group;
    bool has_grant;
    uint32_t grant;
    bool has_deny;
    uint32_t deny;
} MumbleProto_ACL_ChanACL;

typedef struct _MumbleProto_ACL_ChanGroup {
    pb_callback_t name;
    bool has_inherited;
    bool inherited;
    bool has_inherit;
    bool inherit;
    bool has_inheritable;
    bool inheritable;
    pb_callback_t add;
    pb_callback_t remove;
    pb_callback_t inherited_members;
} MumbleProto_ACL_ChanGroup;

typedef struct _MumbleProto_Authenticate {
    bool has_username;
    char username[33];
    bool has_password;
    char password[33];
    pb_callback_t tokens;
    pb_callback_t celt_versions;
    bool has_opus;
    bool opus;
} MumbleProto_Authenticate;

typedef struct _MumbleProto_BanList {
    pb_callback_t bans;
    bool has_query;
    bool query;
} MumbleProto_BanList;

typedef struct _MumbleProto_BanList_BanEntry {
    pb_callback_t address;
    uint32_t mask;
    pb_callback_t name;
    pb_callback_t hash;
    pb_callback_t reason;
    pb_callback_t start;
    bool has_duration;
    uint32_t duration;
} MumbleProto_BanList_BanEntry;

typedef struct _MumbleProto_ChannelRemove {
    uint32_t channel_id;
} MumbleProto_ChannelRemove;

typedef struct _MumbleProto_ChannelState {
    bool has_channel_id;
    uint32_t channel_id;
    bool has_parent;
    uint32_t parent;
    bool has_name;
    char name[33];
    pb_callback_t links;
    bool has_description;
    char description[129];
    pb_callback_t links_add;
    pb_callback_t links_remove;
    bool has_temporary;
    bool temporary;
    bool has_position;
    int32_t position;
    pb_callback_t description_hash;
    bool has_max_users;
    uint32_t max_users;
    bool has_is_enter_restricted;
    bool is_enter_restricted;
    bool has_can_enter;
    bool can_enter;
} MumbleProto_ChannelState;

typedef struct _MumbleProto_CodecVersion {
    int32_t alpha;
    int32_t beta;
    bool prefer_alpha;
    bool has_opus;
    bool opus;
} MumbleProto_CodecVersion;

typedef struct _MumbleProto_ContextAction {
    bool has_session;
    uint32_t session;
    bool has_channel_id;
    uint32_t channel_id;
    pb_callback_t action;
} MumbleProto_ContextAction;

typedef struct _MumbleProto_ContextActionModify {
    pb_callback_t action;
    pb_callback_t text;
    bool has_context;
    uint32_t context;
    bool has_operation;
    MumbleProto_ContextActionModify_Operation operation;
} MumbleProto_ContextActionModify;

typedef PB_BYTES_ARRAY_T(64) MumbleProto_CryptSetup_key_t;
typedef PB_BYTES_ARRAY_T(64) MumbleProto_CryptSetup_client_nonce_t;
typedef PB_BYTES_ARRAY_T(64) MumbleProto_CryptSetup_server_nonce_t;
typedef struct _MumbleProto_CryptSetup {
    bool has_key;
    MumbleProto_CryptSetup_key_t key;
    bool has_client_nonce;
    MumbleProto_CryptSetup_client_nonce_t client_nonce;
    bool has_server_nonce;
    MumbleProto_CryptSetup_server_nonce_t server_nonce;
} MumbleProto_CryptSetup;

typedef struct _MumbleProto_PermissionDenied {
    bool has_permission;
    uint32_t permission;
    bool has_channel_id;
    uint32_t channel_id;
    bool has_session;
    uint32_t session;
    bool has_reason;
    char reason[33];
    bool has_type;
    MumbleProto_PermissionDenied_DenyType type;
    bool has_name;
    char name[33];
} MumbleProto_PermissionDenied;

typedef struct _MumbleProto_PermissionQuery {
    bool has_channel_id;
    uint32_t channel_id;
    bool has_permissions;
    uint32_t permissions;
    bool has_flush;
    bool flush;
} MumbleProto_PermissionQuery;

typedef struct _MumbleProto_Ping {
    bool has_timestamp;
    uint64_t timestamp;
    bool has_good;
    uint32_t good;
    bool has_late;
    uint32_t late;
    bool has_lost;
    uint32_t lost;
    bool has_resync;
    uint32_t resync;
    bool has_udp_packets;
    uint32_t udp_packets;
    bool has_tcp_packets;
    uint32_t tcp_packets;
    bool has_udp_ping_avg;
    float udp_ping_avg;
    bool has_udp_ping_var;
    float udp_ping_var;
    bool has_tcp_ping_avg;
    float tcp_ping_avg;
    bool has_tcp_ping_var;
    float tcp_ping_var;
} MumbleProto_Ping;

typedef struct _MumbleProto_Reject {
    bool has_type;
    MumbleProto_Reject_RejectType type;
    bool has_reason;
    char reason[33];
} MumbleProto_Reject;

typedef struct _MumbleProto_ServerConfig {
    bool has_max_bandwidth;
    uint32_t max_bandwidth;
    pb_callback_t welcome_text;
    bool has_allow_html;
    bool allow_html;
    bool has_message_length;
    uint32_t message_length;
    bool has_image_message_length;
    uint32_t image_message_length;
    bool has_max_users;
    uint32_t max_users;
} MumbleProto_ServerConfig;

typedef struct _MumbleProto_ServerSync {
    bool has_session;
    uint32_t session;
    bool has_max_bandwidth;
    uint32_t max_bandwidth;
    bool has_welcome_text;
    char welcome_text[129];
    bool has_permissions;
    uint64_t permissions;
} MumbleProto_ServerSync;

typedef struct _MumbleProto_SuggestConfig {
    bool has_version;
    uint32_t version;
    bool has_positional;
    bool positional;
    bool has_push_to_talk;
    bool push_to_talk;
} MumbleProto_SuggestConfig;

typedef struct _MumbleProto_TextMessage {
    bool has_actor;
    uint32_t actor;
    pb_callback_t session;
    pb_callback_t channel_id;
    pb_callback_t tree_id;
    char message[33];
} MumbleProto_TextMessage;

typedef struct _MumbleProto_UserList_User {
    uint32_t user_id;
    pb_callback_t name;
    pb_callback_t last_seen;
    bool has_last_channel;
    uint32_t last_channel;
} MumbleProto_UserList_User;

typedef struct _MumbleProto_UserRemove {
    uint32_t session;
    bool has_actor;
    uint32_t actor;
    pb_callback_t reason;
    bool has_ban;
    bool ban;
} MumbleProto_UserRemove;

typedef struct _MumbleProto_UserState {
    bool has_session;
    uint32_t session;
    bool has_actor;
    uint32_t actor;
    bool has_name;
    char name[33];
    bool has_user_id;
    uint32_t user_id;
    bool has_channel_id;
    uint32_t channel_id;
    bool has_mute;
    bool mute;
    bool has_deaf;
    bool deaf;
    bool has_suppress;
    bool suppress;
    bool has_self_mute;
    bool self_mute;
    bool has_self_deaf;
    bool self_deaf;
    pb_callback_t texture;
    pb_callback_t plugin_context;
    pb_callback_t plugin_identity;
    pb_callback_t comment;
    pb_callback_t hash;
    pb_callback_t comment_hash;
    pb_callback_t texture_hash;
    bool has_priority_speaker;
    bool priority_speaker;
    bool has_recording;
    bool recording;
    pb_callback_t temporary_access_tokens;
    pb_callback_t listening_channel_add;
    pb_callback_t listening_channel_remove;
} MumbleProto_UserState;

typedef struct _MumbleProto_UserStats_Stats {
    bool has_good;
    uint32_t good;
    bool has_late;
    uint32_t late;
    bool has_lost;
    uint32_t lost;
    bool has_resync;
    uint32_t resync;
} MumbleProto_UserStats_Stats;

typedef struct _MumbleProto_Version {
    bool has_version;
    uint32_t version;
    bool has_release;
    char release[33];
    bool has_os;
    char os[33];
    bool has_os_version;
    char os_version[33];
} MumbleProto_Version;

typedef struct _MumbleProto_VoiceTarget {
    bool has_id;
    uint32_t id;
    pb_callback_t targets;
} MumbleProto_VoiceTarget;

typedef struct _MumbleProto_VoiceTarget_Target {
    pb_callback_t session;
    bool has_channel_id;
    uint32_t channel_id;
    pb_callback_t group;
    bool has_links;
    bool links;
    bool has_children;
    bool children;
} MumbleProto_VoiceTarget_Target;

typedef struct _MumbleProto_UserStats {
    bool has_session;
    uint32_t session;
    bool has_stats_only;
    bool stats_only;
    pb_callback_t certificates;
    bool has_from_client;
    MumbleProto_UserStats_Stats from_client;
    bool has_from_server;
    MumbleProto_UserStats_Stats from_server;
    bool has_udp_packets;
    uint32_t udp_packets;
    bool has_tcp_packets;
    uint32_t tcp_packets;
    bool has_udp_ping_avg;
    float udp_ping_avg;
    bool has_udp_ping_var;
    float udp_ping_var;
    bool has_tcp_ping_avg;
    float tcp_ping_avg;
    bool has_tcp_ping_var;
    float tcp_ping_var;
    bool has_version;
    MumbleProto_Version version;
    pb_callback_t celt_versions;
    pb_callback_t address;
    bool has_bandwidth;
    uint32_t bandwidth;
    bool has_onlinesecs;
    uint32_t onlinesecs;
    bool has_idlesecs;
    uint32_t idlesecs;
    bool has_strong_certificate;
    bool strong_certificate;
    bool has_opus;
    bool opus;
} MumbleProto_UserStats;


/* Helper constants for enums */
#define _MumbleProto_Reject_RejectType_MIN MumbleProto_Reject_RejectType_None
#define _MumbleProto_Reject_RejectType_MAX MumbleProto_Reject_RejectType_AuthenticatorFail
#define _MumbleProto_Reject_RejectType_ARRAYSIZE ((MumbleProto_Reject_RejectType)(MumbleProto_Reject_RejectType_AuthenticatorFail+1))

#define _MumbleProto_PermissionDenied_DenyType_MIN MumbleProto_PermissionDenied_DenyType_Text
#define _MumbleProto_PermissionDenied_DenyType_MAX MumbleProto_PermissionDenied_DenyType_UserListenerLimit
#define _MumbleProto_PermissionDenied_DenyType_ARRAYSIZE ((MumbleProto_PermissionDenied_DenyType)(MumbleProto_PermissionDenied_DenyType_UserListenerLimit+1))

#define _MumbleProto_ContextActionModify_Context_MIN MumbleProto_ContextActionModify_Context_Server
#define _MumbleProto_ContextActionModify_Context_MAX MumbleProto_ContextActionModify_Context_User
#define _MumbleProto_ContextActionModify_Context_ARRAYSIZE ((MumbleProto_ContextActionModify_Context)(MumbleProto_ContextActionModify_Context_User+1))

#define _MumbleProto_ContextActionModify_Operation_MIN MumbleProto_ContextActionModify_Operation_Add
#define _MumbleProto_ContextActionModify_Operation_MAX MumbleProto_ContextActionModify_Operation_Remove
#define _MumbleProto_ContextActionModify_Operation_ARRAYSIZE ((MumbleProto_ContextActionModify_Operation)(MumbleProto_ContextActionModify_Operation_Remove+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define MumbleProto_Version_init_default         {false, 0, false, "", false, "", false, ""}
#define MumbleProto_UDPTunnel_init_default       {{{NULL}, NULL}}
#define MumbleProto_Authenticate_init_default    {false, "", false, "", {{NULL}, NULL}, {{NULL}, NULL}, false, false}
#define MumbleProto_Ping_init_default            {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define MumbleProto_Reject_init_default          {false, _MumbleProto_Reject_RejectType_MIN, false, ""}
#define MumbleProto_ServerSync_init_default      {false, 0, false, 0, false, "", false, 0}
#define MumbleProto_ChannelRemove_init_default   {0}
#define MumbleProto_ChannelState_init_default    {false, 0, false, 0, false, "", {{NULL}, NULL}, false, "", {{NULL}, NULL}, {{NULL}, NULL}, false, false, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0}
#define MumbleProto_UserRemove_init_default      {0, false, 0, {{NULL}, NULL}, false, 0}
#define MumbleProto_UserState_init_default       {false, 0, false, 0, false, "", false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define MumbleProto_BanList_init_default         {{{NULL}, NULL}, false, false}
#define MumbleProto_BanList_BanEntry_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define MumbleProto_TextMessage_init_default     {false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, ""}
#define MumbleProto_PermissionDenied_init_default {false, 0, false, 0, false, 0, false, "", false, _MumbleProto_PermissionDenied_DenyType_MIN, false, ""}
#define MumbleProto_ACL_init_default             {0, false, true, {{NULL}, NULL}, {{NULL}, NULL}, false, false}
#define MumbleProto_ACL_ChanGroup_init_default   {{{NULL}, NULL}, false, true, false, true, false, true, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define MumbleProto_ACL_ChanACL_init_default     {false, true, false, true, false, true, false, 0, {{NULL}, NULL}, false, 0, false, 0}
#define MumbleProto_QueryUsers_init_default      {{{NULL}, NULL}, {{NULL}, NULL}}
#define MumbleProto_CryptSetup_init_default      {false, {0, {0}}, false, {0, {0}}, false, {0, {0}}}
#define MumbleProto_ContextActionModify_init_default {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, _MumbleProto_ContextActionModify_Operation_MIN}
#define MumbleProto_ContextAction_init_default   {false, 0, false, 0, {{NULL}, NULL}}
#define MumbleProto_UserList_init_default        {{{NULL}, NULL}}
#define MumbleProto_UserList_User_init_default   {0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define MumbleProto_VoiceTarget_init_default     {false, 0, {{NULL}, NULL}}
#define MumbleProto_VoiceTarget_Target_init_default {{{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, false, false, false}
#define MumbleProto_PermissionQuery_init_default {false, 0, false, 0, false, false}
#define MumbleProto_CodecVersion_init_default    {0, 0, true, false, false}
#define MumbleProto_UserStats_init_default       {false, 0, false, false, {{NULL}, NULL}, false, MumbleProto_UserStats_Stats_init_default, false, MumbleProto_UserStats_Stats_init_default, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, MumbleProto_Version_init_default, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, false, false, false}
#define MumbleProto_UserStats_Stats_init_default {false, 0, false, 0, false, 0, false, 0}
#define MumbleProto_RequestBlob_init_default     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define MumbleProto_ServerConfig_init_default    {false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0}
#define MumbleProto_SuggestConfig_init_default   {false, 0, false, 0, false, 0}
#define MumbleProto_Version_init_zero            {false, 0, false, "", false, "", false, ""}
#define MumbleProto_UDPTunnel_init_zero          {{{NULL}, NULL}}
#define MumbleProto_Authenticate_init_zero       {false, "", false, "", {{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define MumbleProto_Ping_init_zero               {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define MumbleProto_Reject_init_zero             {false, _MumbleProto_Reject_RejectType_MIN, false, ""}
#define MumbleProto_ServerSync_init_zero         {false, 0, false, 0, false, "", false, 0}
#define MumbleProto_ChannelRemove_init_zero      {0}
#define MumbleProto_ChannelState_init_zero       {false, 0, false, 0, false, "", {{NULL}, NULL}, false, "", {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0}
#define MumbleProto_UserRemove_init_zero         {0, false, 0, {{NULL}, NULL}, false, 0}
#define MumbleProto_UserState_init_zero          {false, 0, false, 0, false, "", false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define MumbleProto_BanList_init_zero            {{{NULL}, NULL}, false, 0}
#define MumbleProto_BanList_BanEntry_init_zero   {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define MumbleProto_TextMessage_init_zero        {false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, ""}
#define MumbleProto_PermissionDenied_init_zero   {false, 0, false, 0, false, 0, false, "", false, _MumbleProto_PermissionDenied_DenyType_MIN, false, ""}
#define MumbleProto_ACL_init_zero                {0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define MumbleProto_ACL_ChanGroup_init_zero      {{{NULL}, NULL}, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define MumbleProto_ACL_ChanACL_init_zero        {false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0}
#define MumbleProto_QueryUsers_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}}
#define MumbleProto_CryptSetup_init_zero         {false, {0, {0}}, false, {0, {0}}, false, {0, {0}}}
#define MumbleProto_ContextActionModify_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, _MumbleProto_ContextActionModify_Operation_MIN}
#define MumbleProto_ContextAction_init_zero      {false, 0, false, 0, {{NULL}, NULL}}
#define MumbleProto_UserList_init_zero           {{{NULL}, NULL}}
#define MumbleProto_UserList_User_init_zero      {0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define MumbleProto_VoiceTarget_init_zero        {false, 0, {{NULL}, NULL}}
#define MumbleProto_VoiceTarget_Target_init_zero {{{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, false, 0}
#define MumbleProto_PermissionQuery_init_zero    {false, 0, false, 0, false, 0}
#define MumbleProto_CodecVersion_init_zero       {0, 0, 0, false, 0}
#define MumbleProto_UserStats_init_zero          {false, 0, false, 0, {{NULL}, NULL}, false, MumbleProto_UserStats_Stats_init_zero, false, MumbleProto_UserStats_Stats_init_zero, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, MumbleProto_Version_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0}
#define MumbleProto_UserStats_Stats_init_zero    {false, 0, false, 0, false, 0, false, 0}
#define MumbleProto_RequestBlob_init_zero        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define MumbleProto_ServerConfig_init_zero       {false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0}
#define MumbleProto_SuggestConfig_init_zero      {false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MumbleProto_QueryUsers_ids_tag           1
#define MumbleProto_QueryUsers_names_tag         2
#define MumbleProto_RequestBlob_session_texture_tag 1
#define MumbleProto_RequestBlob_session_comment_tag 2
#define MumbleProto_RequestBlob_channel_description_tag 3
#define MumbleProto_UDPTunnel_packet_tag         1
#define MumbleProto_UserList_users_tag           1
#define MumbleProto_ACL_channel_id_tag           1
#define MumbleProto_ACL_inherit_acls_tag         2
#define MumbleProto_ACL_groups_tag               3
#define MumbleProto_ACL_acls_tag                 4
#define MumbleProto_ACL_query_tag                5
#define MumbleProto_ACL_ChanACL_apply_here_tag   1
#define MumbleProto_ACL_ChanACL_apply_subs_tag   2
#define MumbleProto_ACL_ChanACL_inherited_tag    3
#define MumbleProto_ACL_ChanACL_user_id_tag      4
#define MumbleProto_ACL_ChanACL_group_tag        5
#define MumbleProto_ACL_ChanACL_grant_tag        6
#define MumbleProto_ACL_ChanACL_deny_tag         7
#define MumbleProto_ACL_ChanGroup_name_tag       1
#define MumbleProto_ACL_ChanGroup_inherited_tag  2
#define MumbleProto_ACL_ChanGroup_inherit_tag    3
#define MumbleProto_ACL_ChanGroup_inheritable_tag 4
#define MumbleProto_ACL_ChanGroup_add_tag        5
#define MumbleProto_ACL_ChanGroup_remove_tag     6
#define MumbleProto_ACL_ChanGroup_inherited_members_tag 7
#define MumbleProto_Authenticate_username_tag    1
#define MumbleProto_Authenticate_password_tag    2
#define MumbleProto_Authenticate_tokens_tag      3
#define MumbleProto_Authenticate_celt_versions_tag 4
#define MumbleProto_Authenticate_opus_tag        5
#define MumbleProto_BanList_bans_tag             1
#define MumbleProto_BanList_query_tag            2
#define MumbleProto_BanList_BanEntry_address_tag 1
#define MumbleProto_BanList_BanEntry_mask_tag    2
#define MumbleProto_BanList_BanEntry_name_tag    3
#define MumbleProto_BanList_BanEntry_hash_tag    4
#define MumbleProto_BanList_BanEntry_reason_tag  5
#define MumbleProto_BanList_BanEntry_start_tag   6
#define MumbleProto_BanList_BanEntry_duration_tag 7
#define MumbleProto_ChannelRemove_channel_id_tag 1
#define MumbleProto_ChannelState_channel_id_tag  1
#define MumbleProto_ChannelState_parent_tag      2
#define MumbleProto_ChannelState_name_tag        3
#define MumbleProto_ChannelState_links_tag       4
#define MumbleProto_ChannelState_description_tag 5
#define MumbleProto_ChannelState_links_add_tag   6
#define MumbleProto_ChannelState_links_remove_tag 7
#define MumbleProto_ChannelState_temporary_tag   8
#define MumbleProto_ChannelState_position_tag    9
#define MumbleProto_ChannelState_description_hash_tag 10
#define MumbleProto_ChannelState_max_users_tag   11
#define MumbleProto_ChannelState_is_enter_restricted_tag 12
#define MumbleProto_ChannelState_can_enter_tag   13
#define MumbleProto_CodecVersion_alpha_tag       1
#define MumbleProto_CodecVersion_beta_tag        2
#define MumbleProto_CodecVersion_prefer_alpha_tag 3
#define MumbleProto_CodecVersion_opus_tag        4
#define MumbleProto_ContextAction_session_tag    1
#define MumbleProto_ContextAction_channel_id_tag 2
#define MumbleProto_ContextAction_action_tag     3
#define MumbleProto_ContextActionModify_action_tag 1
#define MumbleProto_ContextActionModify_text_tag 2
#define MumbleProto_ContextActionModify_context_tag 3
#define MumbleProto_ContextActionModify_operation_tag 4
#define MumbleProto_CryptSetup_key_tag           1
#define MumbleProto_CryptSetup_client_nonce_tag  2
#define MumbleProto_CryptSetup_server_nonce_tag  3
#define MumbleProto_PermissionDenied_permission_tag 1
#define MumbleProto_PermissionDenied_channel_id_tag 2
#define MumbleProto_PermissionDenied_session_tag 3
#define MumbleProto_PermissionDenied_reason_tag  4
#define MumbleProto_PermissionDenied_type_tag    5
#define MumbleProto_PermissionDenied_name_tag    6
#define MumbleProto_PermissionQuery_channel_id_tag 1
#define MumbleProto_PermissionQuery_permissions_tag 2
#define MumbleProto_PermissionQuery_flush_tag    3
#define MumbleProto_Ping_timestamp_tag           1
#define MumbleProto_Ping_good_tag                2
#define MumbleProto_Ping_late_tag                3
#define MumbleProto_Ping_lost_tag                4
#define MumbleProto_Ping_resync_tag              5
#define MumbleProto_Ping_udp_packets_tag         6
#define MumbleProto_Ping_tcp_packets_tag         7
#define MumbleProto_Ping_udp_ping_avg_tag        8
#define MumbleProto_Ping_udp_ping_var_tag        9
#define MumbleProto_Ping_tcp_ping_avg_tag        10
#define MumbleProto_Ping_tcp_ping_var_tag        11
#define MumbleProto_Reject_type_tag              1
#define MumbleProto_Reject_reason_tag            2
#define MumbleProto_ServerConfig_max_bandwidth_tag 1
#define MumbleProto_ServerConfig_welcome_text_tag 2
#define MumbleProto_ServerConfig_allow_html_tag  3
#define MumbleProto_ServerConfig_message_length_tag 4
#define MumbleProto_ServerConfig_image_message_length_tag 5
#define MumbleProto_ServerConfig_max_users_tag   6
#define MumbleProto_ServerSync_session_tag       1
#define MumbleProto_ServerSync_max_bandwidth_tag 2
#define MumbleProto_ServerSync_welcome_text_tag  3
#define MumbleProto_ServerSync_permissions_tag   4
#define MumbleProto_SuggestConfig_version_tag    1
#define MumbleProto_SuggestConfig_positional_tag 2
#define MumbleProto_SuggestConfig_push_to_talk_tag 3
#define MumbleProto_TextMessage_actor_tag        1
#define MumbleProto_TextMessage_session_tag      2
#define MumbleProto_TextMessage_channel_id_tag   3
#define MumbleProto_TextMessage_tree_id_tag      4
#define MumbleProto_TextMessage_message_tag      5
#define MumbleProto_UserList_User_user_id_tag    1
#define MumbleProto_UserList_User_name_tag       2
#define MumbleProto_UserList_User_last_seen_tag  3
#define MumbleProto_UserList_User_last_channel_tag 4
#define MumbleProto_UserRemove_session_tag       1
#define MumbleProto_UserRemove_actor_tag         2
#define MumbleProto_UserRemove_reason_tag        3
#define MumbleProto_UserRemove_ban_tag           4
#define MumbleProto_UserState_session_tag        1
#define MumbleProto_UserState_actor_tag          2
#define MumbleProto_UserState_name_tag           3
#define MumbleProto_UserState_user_id_tag        4
#define MumbleProto_UserState_channel_id_tag     5
#define MumbleProto_UserState_mute_tag           6
#define MumbleProto_UserState_deaf_tag           7
#define MumbleProto_UserState_suppress_tag       8
#define MumbleProto_UserState_self_mute_tag      9
#define MumbleProto_UserState_self_deaf_tag      10
#define MumbleProto_UserState_texture_tag        11
#define MumbleProto_UserState_plugin_context_tag 12
#define MumbleProto_UserState_plugin_identity_tag 13
#define MumbleProto_UserState_comment_tag        14
#define MumbleProto_UserState_hash_tag           15
#define MumbleProto_UserState_comment_hash_tag   16
#define MumbleProto_UserState_texture_hash_tag   17
#define MumbleProto_UserState_priority_speaker_tag 18
#define MumbleProto_UserState_recording_tag      19
#define MumbleProto_UserState_temporary_access_tokens_tag 20
#define MumbleProto_UserState_listening_channel_add_tag 21
#define MumbleProto_UserState_listening_channel_remove_tag 22
#define MumbleProto_UserStats_Stats_good_tag     1
#define MumbleProto_UserStats_Stats_late_tag     2
#define MumbleProto_UserStats_Stats_lost_tag     3
#define MumbleProto_UserStats_Stats_resync_tag   4
#define MumbleProto_Version_version_tag          1
#define MumbleProto_Version_release_tag          2
#define MumbleProto_Version_os_tag               3
#define MumbleProto_Version_os_version_tag       4
#define MumbleProto_VoiceTarget_id_tag           1
#define MumbleProto_VoiceTarget_targets_tag      2
#define MumbleProto_VoiceTarget_Target_session_tag 1
#define MumbleProto_VoiceTarget_Target_channel_id_tag 2
#define MumbleProto_VoiceTarget_Target_group_tag 3
#define MumbleProto_VoiceTarget_Target_links_tag 4
#define MumbleProto_VoiceTarget_Target_children_tag 5
#define MumbleProto_UserStats_session_tag        1
#define MumbleProto_UserStats_stats_only_tag     2
#define MumbleProto_UserStats_certificates_tag   3
#define MumbleProto_UserStats_from_client_tag    4
#define MumbleProto_UserStats_from_server_tag    5
#define MumbleProto_UserStats_udp_packets_tag    6
#define MumbleProto_UserStats_tcp_packets_tag    7
#define MumbleProto_UserStats_udp_ping_avg_tag   8
#define MumbleProto_UserStats_udp_ping_var_tag   9
#define MumbleProto_UserStats_tcp_ping_avg_tag   10
#define MumbleProto_UserStats_tcp_ping_var_tag   11
#define MumbleProto_UserStats_version_tag        12
#define MumbleProto_UserStats_celt_versions_tag  13
#define MumbleProto_UserStats_address_tag        14
#define MumbleProto_UserStats_bandwidth_tag      15
#define MumbleProto_UserStats_onlinesecs_tag     16
#define MumbleProto_UserStats_idlesecs_tag       17
#define MumbleProto_UserStats_strong_certificate_tag 18
#define MumbleProto_UserStats_opus_tag           19

/* Struct field encoding specification for nanopb */
#define MumbleProto_Version_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   version,           1) \
X(a, STATIC,   OPTIONAL, STRING,   release,           2) \
X(a, STATIC,   OPTIONAL, STRING,   os,                3) \
X(a, STATIC,   OPTIONAL, STRING,   os_version,        4)
#define MumbleProto_Version_CALLBACK NULL
#define MumbleProto_Version_DEFAULT NULL

#define MumbleProto_UDPTunnel_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, BYTES,    packet,            1)
#define MumbleProto_UDPTunnel_CALLBACK pb_default_field_callback
#define MumbleProto_UDPTunnel_DEFAULT NULL

#define MumbleProto_Authenticate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   username,          1) \
X(a, STATIC,   OPTIONAL, STRING,   password,          2) \
X(a, CALLBACK, REPEATED, STRING,   tokens,            3) \
X(a, CALLBACK, REPEATED, INT32,    celt_versions,     4) \
X(a, STATIC,   OPTIONAL, BOOL,     opus,              5)
#define MumbleProto_Authenticate_CALLBACK pb_default_field_callback
#define MumbleProto_Authenticate_DEFAULT (const pb_byte_t*)"\x28\x00\x00"

#define MumbleProto_Ping_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   timestamp,         1) \
X(a, STATIC,   OPTIONAL, UINT32,   good,              2) \
X(a, STATIC,   OPTIONAL, UINT32,   late,              3) \
X(a, STATIC,   OPTIONAL, UINT32,   lost,              4) \
X(a, STATIC,   OPTIONAL, UINT32,   resync,            5) \
X(a, STATIC,   OPTIONAL, UINT32,   udp_packets,       6) \
X(a, STATIC,   OPTIONAL, UINT32,   tcp_packets,       7) \
X(a, STATIC,   OPTIONAL, FLOAT,    udp_ping_avg,      8) \
X(a, STATIC,   OPTIONAL, FLOAT,    udp_ping_var,      9) \
X(a, STATIC,   OPTIONAL, FLOAT,    tcp_ping_avg,     10) \
X(a, STATIC,   OPTIONAL, FLOAT,    tcp_ping_var,     11)
#define MumbleProto_Ping_CALLBACK NULL
#define MumbleProto_Ping_DEFAULT NULL

#define MumbleProto_Reject_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, STRING,   reason,            2)
#define MumbleProto_Reject_CALLBACK NULL
#define MumbleProto_Reject_DEFAULT NULL

#define MumbleProto_ServerSync_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   session,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   max_bandwidth,     2) \
X(a, STATIC,   OPTIONAL, STRING,   welcome_text,      3) \
X(a, STATIC,   OPTIONAL, UINT64,   permissions,       4)
#define MumbleProto_ServerSync_CALLBACK NULL
#define MumbleProto_ServerSync_DEFAULT NULL

#define MumbleProto_ChannelRemove_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   channel_id,        1)
#define MumbleProto_ChannelRemove_CALLBACK NULL
#define MumbleProto_ChannelRemove_DEFAULT NULL

#define MumbleProto_ChannelState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   channel_id,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   parent,            2) \
X(a, STATIC,   OPTIONAL, STRING,   name,              3) \
X(a, CALLBACK, REPEATED, UINT32,   links,             4) \
X(a, STATIC,   OPTIONAL, STRING,   description,       5) \
X(a, CALLBACK, REPEATED, UINT32,   links_add,         6) \
X(a, CALLBACK, REPEATED, UINT32,   links_remove,      7) \
X(a, STATIC,   OPTIONAL, BOOL,     temporary,         8) \
X(a, STATIC,   OPTIONAL, INT32,    position,          9) \
X(a, CALLBACK, OPTIONAL, BYTES,    description_hash,  10) \
X(a, STATIC,   OPTIONAL, UINT32,   max_users,        11) \
X(a, STATIC,   OPTIONAL, BOOL,     is_enter_restricted,  12) \
X(a, STATIC,   OPTIONAL, BOOL,     can_enter,        13)
#define MumbleProto_ChannelState_CALLBACK pb_default_field_callback
#define MumbleProto_ChannelState_DEFAULT (const pb_byte_t*)"\x40\x00\x48\x00\x00"

#define MumbleProto_UserRemove_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   session,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   actor,             2) \
X(a, CALLBACK, OPTIONAL, STRING,   reason,            3) \
X(a, STATIC,   OPTIONAL, BOOL,     ban,               4)
#define MumbleProto_UserRemove_CALLBACK pb_default_field_callback
#define MumbleProto_UserRemove_DEFAULT NULL

#define MumbleProto_UserState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   session,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   actor,             2) \
X(a, STATIC,   OPTIONAL, STRING,   name,              3) \
X(a, STATIC,   OPTIONAL, UINT32,   user_id,           4) \
X(a, STATIC,   OPTIONAL, UINT32,   channel_id,        5) \
X(a, STATIC,   OPTIONAL, BOOL,     mute,              6) \
X(a, STATIC,   OPTIONAL, BOOL,     deaf,              7) \
X(a, STATIC,   OPTIONAL, BOOL,     suppress,          8) \
X(a, STATIC,   OPTIONAL, BOOL,     self_mute,         9) \
X(a, STATIC,   OPTIONAL, BOOL,     self_deaf,        10) \
X(a, CALLBACK, OPTIONAL, BYTES,    texture,          11) \
X(a, CALLBACK, OPTIONAL, BYTES,    plugin_context,   12) \
X(a, CALLBACK, OPTIONAL, STRING,   plugin_identity,  13) \
X(a, CALLBACK, OPTIONAL, STRING,   comment,          14) \
X(a, CALLBACK, OPTIONAL, STRING,   hash,             15) \
X(a, CALLBACK, OPTIONAL, BYTES,    comment_hash,     16) \
X(a, CALLBACK, OPTIONAL, BYTES,    texture_hash,     17) \
X(a, STATIC,   OPTIONAL, BOOL,     priority_speaker,  18) \
X(a, STATIC,   OPTIONAL, BOOL,     recording,        19) \
X(a, CALLBACK, REPEATED, STRING,   temporary_access_tokens,  20) \
X(a, CALLBACK, REPEATED, UINT32,   listening_channel_add,  21) \
X(a, CALLBACK, REPEATED, UINT32,   listening_channel_remove,  22)
#define MumbleProto_UserState_CALLBACK pb_default_field_callback
#define MumbleProto_UserState_DEFAULT NULL

#define MumbleProto_BanList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  bans,              1) \
X(a, STATIC,   OPTIONAL, BOOL,     query,             2)
#define MumbleProto_BanList_CALLBACK pb_default_field_callback
#define MumbleProto_BanList_DEFAULT (const pb_byte_t*)"\x10\x00\x00"
#define MumbleProto_BanList_bans_MSGTYPE MumbleProto_BanList_BanEntry

#define MumbleProto_BanList_BanEntry_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, BYTES,    address,           1) \
X(a, STATIC,   REQUIRED, UINT32,   mask,              2) \
X(a, CALLBACK, OPTIONAL, STRING,   name,              3) \
X(a, CALLBACK, OPTIONAL, STRING,   hash,              4) \
X(a, CALLBACK, OPTIONAL, STRING,   reason,            5) \
X(a, CALLBACK, OPTIONAL, STRING,   start,             6) \
X(a, STATIC,   OPTIONAL, UINT32,   duration,          7)
#define MumbleProto_BanList_BanEntry_CALLBACK pb_default_field_callback
#define MumbleProto_BanList_BanEntry_DEFAULT NULL

#define MumbleProto_TextMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   actor,             1) \
X(a, CALLBACK, REPEATED, UINT32,   session,           2) \
X(a, CALLBACK, REPEATED, UINT32,   channel_id,        3) \
X(a, CALLBACK, REPEATED, UINT32,   tree_id,           4) \
X(a, STATIC,   REQUIRED, STRING,   message,           5)
#define MumbleProto_TextMessage_CALLBACK pb_default_field_callback
#define MumbleProto_TextMessage_DEFAULT NULL

#define MumbleProto_PermissionDenied_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   permission,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   channel_id,        2) \
X(a, STATIC,   OPTIONAL, UINT32,   session,           3) \
X(a, STATIC,   OPTIONAL, STRING,   reason,            4) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              5) \
X(a, STATIC,   OPTIONAL, STRING,   name,              6)
#define MumbleProto_PermissionDenied_CALLBACK NULL
#define MumbleProto_PermissionDenied_DEFAULT NULL

#define MumbleProto_ACL_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   channel_id,        1) \
X(a, STATIC,   OPTIONAL, BOOL,     inherit_acls,      2) \
X(a, CALLBACK, REPEATED, MESSAGE,  groups,            3) \
X(a, CALLBACK, REPEATED, MESSAGE,  acls,              4) \
X(a, STATIC,   OPTIONAL, BOOL,     query,             5)
#define MumbleProto_ACL_CALLBACK pb_default_field_callback
#define MumbleProto_ACL_DEFAULT (const pb_byte_t*)"\x10\x01\x28\x00\x00"
#define MumbleProto_ACL_groups_MSGTYPE MumbleProto_ACL_ChanGroup
#define MumbleProto_ACL_acls_MSGTYPE MumbleProto_ACL_ChanACL

#define MumbleProto_ACL_ChanGroup_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, BOOL,     inherited,         2) \
X(a, STATIC,   OPTIONAL, BOOL,     inherit,           3) \
X(a, STATIC,   OPTIONAL, BOOL,     inheritable,       4) \
X(a, CALLBACK, REPEATED, UINT32,   add,               5) \
X(a, CALLBACK, REPEATED, UINT32,   remove,            6) \
X(a, CALLBACK, REPEATED, UINT32,   inherited_members,   7)
#define MumbleProto_ACL_ChanGroup_CALLBACK pb_default_field_callback
#define MumbleProto_ACL_ChanGroup_DEFAULT (const pb_byte_t*)"\x10\x01\x18\x01\x20\x01\x00"

#define MumbleProto_ACL_ChanACL_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     apply_here,        1) \
X(a, STATIC,   OPTIONAL, BOOL,     apply_subs,        2) \
X(a, STATIC,   OPTIONAL, BOOL,     inherited,         3) \
X(a, STATIC,   OPTIONAL, UINT32,   user_id,           4) \
X(a, CALLBACK, OPTIONAL, STRING,   group,             5) \
X(a, STATIC,   OPTIONAL, UINT32,   grant,             6) \
X(a, STATIC,   OPTIONAL, UINT32,   deny,              7)
#define MumbleProto_ACL_ChanACL_CALLBACK pb_default_field_callback
#define MumbleProto_ACL_ChanACL_DEFAULT (const pb_byte_t*)"\x08\x01\x10\x01\x18\x01\x00"

#define MumbleProto_QueryUsers_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   ids,               1) \
X(a, CALLBACK, REPEATED, STRING,   names,             2)
#define MumbleProto_QueryUsers_CALLBACK pb_default_field_callback
#define MumbleProto_QueryUsers_DEFAULT NULL

#define MumbleProto_CryptSetup_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BYTES,    key,               1) \
X(a, STATIC,   OPTIONAL, BYTES,    client_nonce,      2) \
X(a, STATIC,   OPTIONAL, BYTES,    server_nonce,      3)
#define MumbleProto_CryptSetup_CALLBACK NULL
#define MumbleProto_CryptSetup_DEFAULT NULL

#define MumbleProto_ContextActionModify_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   action,            1) \
X(a, CALLBACK, OPTIONAL, STRING,   text,              2) \
X(a, STATIC,   OPTIONAL, UINT32,   context,           3) \
X(a, STATIC,   OPTIONAL, UENUM,    operation,         4)
#define MumbleProto_ContextActionModify_CALLBACK pb_default_field_callback
#define MumbleProto_ContextActionModify_DEFAULT NULL

#define MumbleProto_ContextAction_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   session,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   channel_id,        2) \
X(a, CALLBACK, REQUIRED, STRING,   action,            3)
#define MumbleProto_ContextAction_CALLBACK pb_default_field_callback
#define MumbleProto_ContextAction_DEFAULT NULL

#define MumbleProto_UserList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  users,             1)
#define MumbleProto_UserList_CALLBACK pb_default_field_callback
#define MumbleProto_UserList_DEFAULT NULL
#define MumbleProto_UserList_users_MSGTYPE MumbleProto_UserList_User

#define MumbleProto_UserList_User_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   user_id,           1) \
X(a, CALLBACK, OPTIONAL, STRING,   name,              2) \
X(a, CALLBACK, OPTIONAL, STRING,   last_seen,         3) \
X(a, STATIC,   OPTIONAL, UINT32,   last_channel,      4)
#define MumbleProto_UserList_User_CALLBACK pb_default_field_callback
#define MumbleProto_UserList_User_DEFAULT NULL

#define MumbleProto_VoiceTarget_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   id,                1) \
X(a, CALLBACK, REPEATED, MESSAGE,  targets,           2)
#define MumbleProto_VoiceTarget_CALLBACK pb_default_field_callback
#define MumbleProto_VoiceTarget_DEFAULT NULL
#define MumbleProto_VoiceTarget_targets_MSGTYPE MumbleProto_VoiceTarget_Target

#define MumbleProto_VoiceTarget_Target_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   session,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   channel_id,        2) \
X(a, CALLBACK, OPTIONAL, STRING,   group,             3) \
X(a, STATIC,   OPTIONAL, BOOL,     links,             4) \
X(a, STATIC,   OPTIONAL, BOOL,     children,          5)
#define MumbleProto_VoiceTarget_Target_CALLBACK pb_default_field_callback
#define MumbleProto_VoiceTarget_Target_DEFAULT (const pb_byte_t*)"\x20\x00\x28\x00\x00"

#define MumbleProto_PermissionQuery_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   channel_id,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   permissions,       2) \
X(a, STATIC,   OPTIONAL, BOOL,     flush,             3)
#define MumbleProto_PermissionQuery_CALLBACK NULL
#define MumbleProto_PermissionQuery_DEFAULT (const pb_byte_t*)"\x18\x00\x00"

#define MumbleProto_CodecVersion_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    alpha,             1) \
X(a, STATIC,   REQUIRED, INT32,    beta,              2) \
X(a, STATIC,   REQUIRED, BOOL,     prefer_alpha,      3) \
X(a, STATIC,   OPTIONAL, BOOL,     opus,              4)
#define MumbleProto_CodecVersion_CALLBACK NULL
#define MumbleProto_CodecVersion_DEFAULT (const pb_byte_t*)"\x18\x01\x20\x00\x00"

#define MumbleProto_UserStats_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   session,           1) \
X(a, STATIC,   OPTIONAL, BOOL,     stats_only,        2) \
X(a, CALLBACK, REPEATED, BYTES,    certificates,      3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  from_client,       4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  from_server,       5) \
X(a, STATIC,   OPTIONAL, UINT32,   udp_packets,       6) \
X(a, STATIC,   OPTIONAL, UINT32,   tcp_packets,       7) \
X(a, STATIC,   OPTIONAL, FLOAT,    udp_ping_avg,      8) \
X(a, STATIC,   OPTIONAL, FLOAT,    udp_ping_var,      9) \
X(a, STATIC,   OPTIONAL, FLOAT,    tcp_ping_avg,     10) \
X(a, STATIC,   OPTIONAL, FLOAT,    tcp_ping_var,     11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,          12) \
X(a, CALLBACK, REPEATED, INT32,    celt_versions,    13) \
X(a, CALLBACK, OPTIONAL, BYTES,    address,          14) \
X(a, STATIC,   OPTIONAL, UINT32,   bandwidth,        15) \
X(a, STATIC,   OPTIONAL, UINT32,   onlinesecs,       16) \
X(a, STATIC,   OPTIONAL, UINT32,   idlesecs,         17) \
X(a, STATIC,   OPTIONAL, BOOL,     strong_certificate,  18) \
X(a, STATIC,   OPTIONAL, BOOL,     opus,             19)
#define MumbleProto_UserStats_CALLBACK pb_default_field_callback
#define MumbleProto_UserStats_DEFAULT (const pb_byte_t*)"\x10\x00\x90\x01\x00\x98\x01\x00\x00"
#define MumbleProto_UserStats_from_client_MSGTYPE MumbleProto_UserStats_Stats
#define MumbleProto_UserStats_from_server_MSGTYPE MumbleProto_UserStats_Stats
#define MumbleProto_UserStats_version_MSGTYPE MumbleProto_Version

#define MumbleProto_UserStats_Stats_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   good,              1) \
X(a, STATIC,   OPTIONAL, UINT32,   late,              2) \
X(a, STATIC,   OPTIONAL, UINT32,   lost,              3) \
X(a, STATIC,   OPTIONAL, UINT32,   resync,            4)
#define MumbleProto_UserStats_Stats_CALLBACK NULL
#define MumbleProto_UserStats_Stats_DEFAULT NULL

#define MumbleProto_RequestBlob_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   session_texture,   1) \
X(a, CALLBACK, REPEATED, UINT32,   session_comment,   2) \
X(a, CALLBACK, REPEATED, UINT32,   channel_description,   3)
#define MumbleProto_RequestBlob_CALLBACK pb_default_field_callback
#define MumbleProto_RequestBlob_DEFAULT NULL

#define MumbleProto_ServerConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   max_bandwidth,     1) \
X(a, CALLBACK, OPTIONAL, STRING,   welcome_text,      2) \
X(a, STATIC,   OPTIONAL, BOOL,     allow_html,        3) \
X(a, STATIC,   OPTIONAL, UINT32,   message_length,    4) \
X(a, STATIC,   OPTIONAL, UINT32,   image_message_length,   5) \
X(a, STATIC,   OPTIONAL, UINT32,   max_users,         6)
#define MumbleProto_ServerConfig_CALLBACK pb_default_field_callback
#define MumbleProto_ServerConfig_DEFAULT NULL

#define MumbleProto_SuggestConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   version,           1) \
X(a, STATIC,   OPTIONAL, BOOL,     positional,        2) \
X(a, STATIC,   OPTIONAL, BOOL,     push_to_talk,      3)
#define MumbleProto_SuggestConfig_CALLBACK NULL
#define MumbleProto_SuggestConfig_DEFAULT NULL

extern const pb_msgdesc_t MumbleProto_Version_msg;
extern const pb_msgdesc_t MumbleProto_UDPTunnel_msg;
extern const pb_msgdesc_t MumbleProto_Authenticate_msg;
extern const pb_msgdesc_t MumbleProto_Ping_msg;
extern const pb_msgdesc_t MumbleProto_Reject_msg;
extern const pb_msgdesc_t MumbleProto_ServerSync_msg;
extern const pb_msgdesc_t MumbleProto_ChannelRemove_msg;
extern const pb_msgdesc_t MumbleProto_ChannelState_msg;
extern const pb_msgdesc_t MumbleProto_UserRemove_msg;
extern const pb_msgdesc_t MumbleProto_UserState_msg;
extern const pb_msgdesc_t MumbleProto_BanList_msg;
extern const pb_msgdesc_t MumbleProto_BanList_BanEntry_msg;
extern const pb_msgdesc_t MumbleProto_TextMessage_msg;
extern const pb_msgdesc_t MumbleProto_PermissionDenied_msg;
extern const pb_msgdesc_t MumbleProto_ACL_msg;
extern const pb_msgdesc_t MumbleProto_ACL_ChanGroup_msg;
extern const pb_msgdesc_t MumbleProto_ACL_ChanACL_msg;
extern const pb_msgdesc_t MumbleProto_QueryUsers_msg;
extern const pb_msgdesc_t MumbleProto_CryptSetup_msg;
extern const pb_msgdesc_t MumbleProto_ContextActionModify_msg;
extern const pb_msgdesc_t MumbleProto_ContextAction_msg;
extern const pb_msgdesc_t MumbleProto_UserList_msg;
extern const pb_msgdesc_t MumbleProto_UserList_User_msg;
extern const pb_msgdesc_t MumbleProto_VoiceTarget_msg;
extern const pb_msgdesc_t MumbleProto_VoiceTarget_Target_msg;
extern const pb_msgdesc_t MumbleProto_PermissionQuery_msg;
extern const pb_msgdesc_t MumbleProto_CodecVersion_msg;
extern const pb_msgdesc_t MumbleProto_UserStats_msg;
extern const pb_msgdesc_t MumbleProto_UserStats_Stats_msg;
extern const pb_msgdesc_t MumbleProto_RequestBlob_msg;
extern const pb_msgdesc_t MumbleProto_ServerConfig_msg;
extern const pb_msgdesc_t MumbleProto_SuggestConfig_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MumbleProto_Version_fields &MumbleProto_Version_msg
#define MumbleProto_UDPTunnel_fields &MumbleProto_UDPTunnel_msg
#define MumbleProto_Authenticate_fields &MumbleProto_Authenticate_msg
#define MumbleProto_Ping_fields &MumbleProto_Ping_msg
#define MumbleProto_Reject_fields &MumbleProto_Reject_msg
#define MumbleProto_ServerSync_fields &MumbleProto_ServerSync_msg
#define MumbleProto_ChannelRemove_fields &MumbleProto_ChannelRemove_msg
#define MumbleProto_ChannelState_fields &MumbleProto_ChannelState_msg
#define MumbleProto_UserRemove_fields &MumbleProto_UserRemove_msg
#define MumbleProto_UserState_fields &MumbleProto_UserState_msg
#define MumbleProto_BanList_fields &MumbleProto_BanList_msg
#define MumbleProto_BanList_BanEntry_fields &MumbleProto_BanList_BanEntry_msg
#define MumbleProto_TextMessage_fields &MumbleProto_TextMessage_msg
#define MumbleProto_PermissionDenied_fields &MumbleProto_PermissionDenied_msg
#define MumbleProto_ACL_fields &MumbleProto_ACL_msg
#define MumbleProto_ACL_ChanGroup_fields &MumbleProto_ACL_ChanGroup_msg
#define MumbleProto_ACL_ChanACL_fields &MumbleProto_ACL_ChanACL_msg
#define MumbleProto_QueryUsers_fields &MumbleProto_QueryUsers_msg
#define MumbleProto_CryptSetup_fields &MumbleProto_CryptSetup_msg
#define MumbleProto_ContextActionModify_fields &MumbleProto_ContextActionModify_msg
#define MumbleProto_ContextAction_fields &MumbleProto_ContextAction_msg
#define MumbleProto_UserList_fields &MumbleProto_UserList_msg
#define MumbleProto_UserList_User_fields &MumbleProto_UserList_User_msg
#define MumbleProto_VoiceTarget_fields &MumbleProto_VoiceTarget_msg
#define MumbleProto_VoiceTarget_Target_fields &MumbleProto_VoiceTarget_Target_msg
#define MumbleProto_PermissionQuery_fields &MumbleProto_PermissionQuery_msg
#define MumbleProto_CodecVersion_fields &MumbleProto_CodecVersion_msg
#define MumbleProto_UserStats_fields &MumbleProto_UserStats_msg
#define MumbleProto_UserStats_Stats_fields &MumbleProto_UserStats_Stats_msg
#define MumbleProto_RequestBlob_fields &MumbleProto_RequestBlob_msg
#define MumbleProto_ServerConfig_fields &MumbleProto_ServerConfig_msg
#define MumbleProto_SuggestConfig_fields &MumbleProto_SuggestConfig_msg

/* Maximum encoded size of messages (where known) */
#define MumbleProto_Version_size                 108
/* MumbleProto_UDPTunnel_size depends on runtime parameters */
/* MumbleProto_Authenticate_size depends on runtime parameters */
#define MumbleProto_Ping_size                    67
#define MumbleProto_Reject_size                  36
#define MumbleProto_ServerSync_size              154
#define MumbleProto_ChannelRemove_size           6
/* MumbleProto_ChannelState_size depends on runtime parameters */
/* MumbleProto_UserRemove_size depends on runtime parameters */
/* MumbleProto_UserState_size depends on runtime parameters */
/* MumbleProto_BanList_size depends on runtime parameters */
/* MumbleProto_BanList_BanEntry_size depends on runtime parameters */
/* MumbleProto_TextMessage_size depends on runtime parameters */
#define MumbleProto_PermissionDenied_size        88
/* MumbleProto_ACL_size depends on runtime parameters */
/* MumbleProto_ACL_ChanGroup_size depends on runtime parameters */
/* MumbleProto_ACL_ChanACL_size depends on runtime parameters */
/* MumbleProto_QueryUsers_size depends on runtime parameters */
#define MumbleProto_CryptSetup_size              198
/* MumbleProto_ContextActionModify_size depends on runtime parameters */
/* MumbleProto_ContextAction_size depends on runtime parameters */
/* MumbleProto_UserList_size depends on runtime parameters */
/* MumbleProto_UserList_User_size depends on runtime parameters */
/* MumbleProto_VoiceTarget_size depends on runtime parameters */
/* MumbleProto_VoiceTarget_Target_size depends on runtime parameters */
#define MumbleProto_PermissionQuery_size         14
#define MumbleProto_CodecVersion_size            26
/* MumbleProto_UserStats_size depends on runtime parameters */
#define MumbleProto_UserStats_Stats_size         24
/* MumbleProto_RequestBlob_size depends on runtime parameters */
/* MumbleProto_ServerConfig_size depends on runtime parameters */
#define MumbleProto_SuggestConfig_size           10

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
