/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev */

#include "mumble.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MumbleProto_Version, MumbleProto_Version, AUTO)


PB_BIND(MumbleProto_UDPTunnel, MumbleProto_UDPTunnel, AUTO)


PB_BIND(MumbleProto_Authenticate, MumbleProto_Authenticate, AUTO)


PB_BIND(MumbleProto_Ping, MumbleProto_Ping, AUTO)


PB_BIND(MumbleProto_Reject, MumbleProto_Reject, AUTO)


PB_BIND(MumbleProto_ServerSync, MumbleProto_ServerSync, AUTO)


PB_BIND(MumbleProto_ChannelRemove, MumbleProto_ChannelRemove, AUTO)


PB_BIND(MumbleProto_ChannelState, MumbleProto_ChannelState, 2)


PB_BIND(MumbleProto_UserRemove, MumbleProto_UserRemove, AUTO)


PB_BIND(MumbleProto_UserState, MumbleProto_UserState, 2)


PB_BIND(MumbleProto_BanList, MumbleProto_BanList, AUTO)


PB_BIND(MumbleProto_BanList_BanEntry, MumbleProto_BanList_BanEntry, AUTO)


PB_BIND(MumbleProto_TextMessage, MumbleProto_TextMessage, AUTO)


PB_BIND(MumbleProto_PermissionDenied, MumbleProto_PermissionDenied, AUTO)


PB_BIND(MumbleProto_ACL, MumbleProto_ACL, AUTO)


PB_BIND(MumbleProto_ACL_ChanGroup, MumbleProto_ACL_ChanGroup, AUTO)


PB_BIND(MumbleProto_ACL_ChanACL, MumbleProto_ACL_ChanACL, AUTO)


PB_BIND(MumbleProto_QueryUsers, MumbleProto_QueryUsers, AUTO)


PB_BIND(MumbleProto_CryptSetup, MumbleProto_CryptSetup, AUTO)


PB_BIND(MumbleProto_ContextActionModify, MumbleProto_ContextActionModify, AUTO)


PB_BIND(MumbleProto_ContextAction, MumbleProto_ContextAction, AUTO)


PB_BIND(MumbleProto_UserList, MumbleProto_UserList, AUTO)


PB_BIND(MumbleProto_UserList_User, MumbleProto_UserList_User, AUTO)


PB_BIND(MumbleProto_VoiceTarget, MumbleProto_VoiceTarget, AUTO)


PB_BIND(MumbleProto_VoiceTarget_Target, MumbleProto_VoiceTarget_Target, AUTO)


PB_BIND(MumbleProto_PermissionQuery, MumbleProto_PermissionQuery, AUTO)


PB_BIND(MumbleProto_CodecVersion, MumbleProto_CodecVersion, AUTO)


PB_BIND(MumbleProto_UserStats, MumbleProto_UserStats, 2)


PB_BIND(MumbleProto_UserStats_Stats, MumbleProto_UserStats_Stats, AUTO)


PB_BIND(MumbleProto_RequestBlob, MumbleProto_RequestBlob, AUTO)


PB_BIND(MumbleProto_ServerConfig, MumbleProto_ServerConfig, AUTO)


PB_BIND(MumbleProto_SuggestConfig, MumbleProto_SuggestConfig, AUTO)







